### ISSUE TITLE
universalize zsh jupyter command line

### ISSUE THREAD

**Issue by pickettj** [pickettj/dot_files#2]
When one installs Jupyter, it [adds a piece of code to the bash profile that allows you to launch Jupyter from the command line, but does not add to zsh](https://medium.com/@sumitmenon/how-to-get-anaconda-to-work-with-oh-my-zsh-on-mac-os-x-7c1c7247d896):

```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/enkidu/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/enkidu/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/enkidu/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/enkidu/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

Is there a good way to universalize the path [in my dot file](https://github.com/pickettj/dot_files/blob/master/.zshrc) so that it works for multiple machines? I've tried subbing `/Users/enkidu/` with both `~` and `$HOME`. @iamlemec , any suggestions?

**Comment by iamlemec** [comment]
I think it's the single quotes on that third line (first uncommented line) that are causing problems. Make that something like:
```
__conda_setup="$($HOME/opt/anaconda3/bin/conda 'shell.zsh' 'hook' 2> /dev/null)"
```

**Comment by pickettj** [comment]
Awesome! Thanks @iamlemec
